#!/bin/bash

echo 'Welcome!  Amsterdam Wolf....'
echo '	'
echo 'filter -- '

cd /home/tomi/Desktop/Arena/USEARCH/Out
# filter reads to max expected error 1 per read
usearch32  -fastq_filter ./merged.fastq  -fastq_maxee 1 -fastaout filtered.fasta  2>&1


