#!/bin/bash

echo 'Welcome!  Amsterdam Wolf....'
echo '	'
echo 'Running fast q info'

cd /home/tomi/Desktop/Arena/USEARCH/fastqfiles/
for fq  in *.fastq;  do
	echo $fq
    echo '----------------------------------------------------------------------------------------------------||||||----- ' 
    usearch32 -fastx_info $fq -output ../fastq_info/$fq
done
